title: commotum
description: "Header & nav (multi-file CSS)"
# For project pages set baseurl: "/your-repo-name"
baseurl: ""
permalink: pretty
markdown: kramdown
collections:
  ideas:
    output: true

defaults:
  - scope:
      path: ""
      type: ideas
    values:
      layout: idea
